In [2]:
df_mantenimiento.to_excel('Mantenimiento.xlsx', index=False, sheet_name='Mantenimiento')

print("Archivo guardado exitosamente.")

Archivo guardado exitosamente.

In [12]:
import pandas as pd

# Cargar el archivo
df_mantenimiento = pd.read_excel('Mantenimiento.xlsx')

# Ver las primeras filas

In [13]:
df_mantenimiento

        Fecha      Maquina Horas_Parada Costo_Reparacion   Turno
0  2026-04-01  Inyectora_1          2.5             $500  Mañana
1  2026-04-01  Extrusora_A            4            $1200  Mañana
2  2026-04-02  Inyectora_1          3,5             $450   Noche
3  2026-04-02  Extrusora_A          NaN            $1300   Tarde
4  2026-04-03     Prensa_H          1.2             $200  Mañana
5  2026-04-04  Inyectora_1            5             $600   Noche
6  2026-04-04  Extrusora_A          2.8             $900   Tarde
7  2026-04-05     Prensa_H          0.5             $150  Mañana
8  2026-04-05  Inyectora_1          1,8             $400   Noche
9  2026-04-06  Extrusora_A          4.2            $1100   Tarde
10 2026-04-07     Prensa_H          NaN             $300  Mañana
11 2026-04-07  Inyectora_1          3.1             $550   Tarde
12 2026-04-08  Extrusora_A          2.2             $850   Noche
13 2026-04-09     Prensa_H          1.5             $250  Mañana
14 2026-04-10  Inyectora_1            4             $700   Tarde
15 2026-04-11  Extrusora_A          2.5             $950  Mañana
16 2026-04-11     Prensa_H          0.8             $180   Noche
17 2026-04-12  Inyectora_1          2,2             $480   Tarde
18 2026-04-13  Extrusora_A          3.7            $1050   Tarde
19 2026-04-14     Prensa_H            1             $220  Mañana

In [14]:
df_mantenimiento.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Fecha             20 non-null     datetime64[us]
 1   Maquina           20 non-null     str
 2   Horas_Parada      18 non-null     object
 3   Costo_Reparacion  20 non-null     str
 4   Turno             20 non-null     str
dtypes: datetime64[us](1), object(1), str(3)
memory usage: 932.0+ bytes

In [16]:
df_mantenimiento['Horas_Parada'] = df_mantenimiento['Horas_Parada'].astype(str).str.replace(',', '.')
df_mantenimiento

        Fecha      Maquina Horas_Parada Costo_Reparacion   Turno
0  2026-04-01  Inyectora_1          2.5             $500  Mañana
1  2026-04-01  Extrusora_A            4            $1200  Mañana
2  2026-04-02  Inyectora_1          3.5             $450   Noche
3  2026-04-02  Extrusora_A          NaN            $1300   Tarde
4  2026-04-03     Prensa_H          1.2             $200  Mañana
5  2026-04-04  Inyectora_1            5             $600   Noche
6  2026-04-04  Extrusora_A          2.8             $900   Tarde
7  2026-04-05     Prensa_H          0.5             $150  Mañana
8  2026-04-05  Inyectora_1          1.8             $400   Noche
9  2026-04-06  Extrusora_A          4.2            $1100   Tarde
10 2026-04-07     Prensa_H          NaN             $300  Mañana
11 2026-04-07  Inyectora_1          3.1             $550   Tarde
12 2026-04-08  Extrusora_A          2.2             $850   Noche
13 2026-04-09     Prensa_H          1.5             $250  Mañana
14 2026-04-10  Inyectora_1            4             $700   Tarde
15 2026-04-11  Extrusora_A          2.5             $950  Mañana
16 2026-04-11     Prensa_H          0.8             $180   Noche
17 2026-04-12  Inyectora_1          2.2             $480   Tarde
18 2026-04-13  Extrusora_A          3.7            $1050   Tarde
19 2026-04-14     Prensa_H            1             $220  Mañana

In [18]:
mediana = df_mantenimiento['Horas_Parada'].median()
df_mantenimiento['Horas_Parada'].fillna(mediana)
df_mantenimiento

TypeError: Cannot perform reduction 'median' with string dtype

In [26]:
df_mantenimiento['Horas_Parada'] = pd.to_numeric(df_mantenimiento['Horas_Parada'], errors='coerce')
df_mantenimiento.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Fecha             20 non-null     datetime64[us]
 1   Maquina           20 non-null     str
 2   Horas_Parada      18 non-null     float64
 3   Costo_Reparacion  20 non-null     float64
 4   Turno             20 non-null     str
dtypes: datetime64[us](1), float64(2), str(2)
memory usage: 932.0 bytes

In [28]:
df_mantenimiento

        Fecha      Maquina  Horas_Parada  Costo_Reparacion   Turno
0  2026-04-01  Inyectora_1           2.5             500.0  Mañana
1  2026-04-01  Extrusora_A           4.0            1200.0  Mañana
2  2026-04-02  Inyectora_1           3.5             450.0   Noche
3  2026-04-02  Extrusora_A           NaN            1300.0   Tarde
4  2026-04-03     Prensa_H           1.2             200.0  Mañana
5  2026-04-04  Inyectora_1           5.0             600.0   Noche
6  2026-04-04  Extrusora_A           2.8             900.0   Tarde
7  2026-04-05     Prensa_H           0.5             150.0  Mañana
8  2026-04-05  Inyectora_1           1.8             400.0   Noche
9  2026-04-06  Extrusora_A           4.2            1100.0   Tarde
10 2026-04-07     Prensa_H           NaN             300.0  Mañana
11 2026-04-07  Inyectora_1           3.1             550.0   Tarde
12 2026-04-08  Extrusora_A           2.2             850.0   Noche
13 2026-04-09     Prensa_H           1.5             250.0  Mañana
14 2026-04-10  Inyectora_1           4.0             700.0   Tarde
15 2026-04-11  Extrusora_A           2.5             950.0  Mañana
16 2026-04-11     Prensa_H           0.8             180.0   Noche
17 2026-04-12  Inyectora_1           2.2             480.0   Tarde
18 2026-04-13  Extrusora_A           3.7            1050.0   Tarde
19 2026-04-14     Prensa_H           1.0             220.0  Mañana

In [31]:
mediana = df_mantenimiento['Horas_Parada'].median()
df_mantenimiento['Horas_Parada'] = df_mantenimiento['Horas_Parada'].fillna(mediana)
df_mantenimiento

        Fecha      Maquina  Horas_Parada  Costo_Reparacion   Turno
0  2026-04-01  Inyectora_1           2.5             500.0  Mañana
1  2026-04-01  Extrusora_A           4.0            1200.0  Mañana
2  2026-04-02  Inyectora_1           3.5             450.0   Noche
3  2026-04-02  Extrusora_A           2.5            1300.0   Tarde
4  2026-04-03     Prensa_H           1.2             200.0  Mañana
5  2026-04-04  Inyectora_1           5.0             600.0   Noche
6  2026-04-04  Extrusora_A           2.8             900.0   Tarde
7  2026-04-05     Prensa_H           0.5             150.0  Mañana
8  2026-04-05  Inyectora_1           1.8             400.0   Noche
9  2026-04-06  Extrusora_A           4.2            1100.0   Tarde
10 2026-04-07     Prensa_H           2.5             300.0  Mañana
11 2026-04-07  Inyectora_1           3.1             550.0   Tarde
12 2026-04-08  Extrusora_A           2.2             850.0   Noche
13 2026-04-09     Prensa_H           1.5             250.0  Mañana
14 2026-04-10  Inyectora_1           4.0             700.0   Tarde
15 2026-04-11  Extrusora_A           2.5             950.0  Mañana
16 2026-04-11     Prensa_H           0.8             180.0   Noche
17 2026-04-12  Inyectora_1           2.2             480.0   Tarde
18 2026-04-13  Extrusora_A           3.7            1050.0   Tarde
19 2026-04-14     Prensa_H           1.0             220.0  Mañana

In [33]:
df_mantenimiento['Costo_Hora'] = df_mantenimiento['Costo_Reparacion'] / df_mantenimiento['Horas_Parada']
df_mantenimiento['Costo_Hora'] = df_mantenimiento['Costo_Hora'].round(2)
df_mantenimiento

        Fecha      Maquina  Horas_Parada  Costo_Reparacion   Turno  Costo_Hora
0  2026-04-01  Inyectora_1           2.5             500.0  Mañana      200.00
1  2026-04-01  Extrusora_A           4.0            1200.0  Mañana      300.00
2  2026-04-02  Inyectora_1           3.5             450.0   Noche      128.57
3  2026-04-02  Extrusora_A           2.5            1300.0   Tarde      520.00
4  2026-04-03     Prensa_H           1.2             200.0  Mañana      166.67
5  2026-04-04  Inyectora_1           5.0             600.0   Noche      120.00
6  2026-04-04  Extrusora_A           2.8             900.0   Tarde      321.43
7  2026-04-05     Prensa_H           0.5             150.0  Mañana      300.00
8  2026-04-05  Inyectora_1           1.8             400.0   Noche      222.22
9  2026-04-06  Extrusora_A           4.2            1100.0   Tarde      261.90
10 2026-04-07     Prensa_H           2.5             300.0  Mañana      120.00
11 2026-04-07  Inyectora_1           3.1             550.0   Tarde      177.42
12 2026-04-08  Extrusora_A           2.2             850.0   Noche      386.36
13 2026-04-09     Prensa_H           1.5             250.0  Mañana      166.67
14 2026-04-10  Inyectora_1           4.0             700.0   Tarde      175.00
15 2026-04-11  Extrusora_A           2.5             950.0  Mañana      380.00
16 2026-04-11     Prensa_H           0.8             180.0   Noche      225.00
17 2026-04-12  Inyectora_1           2.2             480.0   Tarde      218.18
18 2026-04-13  Extrusora_A           3.7            1050.0   Tarde      283.78
19 2026-04-14     Prensa_H           1.0             220.0  Mañana      220.00

In [38]:
Agrupar = df_mantenimiento.groupby('Maquina')['Costo_Hora'].sum()
print(Agrupar)

Maquina
Extrusora_A    2453.47
Inyectora_1    1241.39
Prensa_H       1198.34
Name: Costo_Hora, dtype: float64

In [35]:
Agrupa_Cosot = df_mantenimiento.groupby('Maquina')['Costo_Reparacion'].sum()
print(Agrupa_Cosot)

Maquina
Extrusora_A    7350.0
Inyectora_1    3680.0
Prensa_H       1300.0
Name: Costo_Reparacion, dtype: float64

In [36]:
Agrupaar_Horas = df_mantenimiento.groupby('Maquina')['Horas_Parada'].sum()
print(Agrupaar_Horas)

Maquina
Extrusora_A    21.9
Inyectora_1    22.1
Prensa_H        7.5
Name: Horas_Parada, dtype: float64

In [37]:
df_mantenimiento.to_excel('Mantenimiento_Nuevo.xlsx', index=False, sheet_name='Mantenimiento')

print("Archivo guardado exitosamente.")

Archivo guardado exitosamente.